baseURL = 'https://blog.trim21.me/'
languageCode = 'zh-cn'
title = "Trim21's"
theme = "PaperMod"
enableRobotsTXT = true
enableGitInfo = true
titleCaseStyle = 'none'

[pagination]
pagerSize = 20

# [services]
# [services.disqus]
# shortname = "trim21"
# [markup.highlight]
# style = "github-dark"
[params]
comments = true
DateFormat = "2006-01-02"
hidemeta = false

[params.homeInfoParams]
Title = "Hi there"

[[params.socialIcons]]
name = 'github'
url = "https://github.com/trim21"

[analytics.google]
SiteVerificationTag = "UA-91727260-1"

[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"

# [[menu.main]]
# name = "About"
# weight = 2
# url = "about/"
