baseURL = 'https://blog.trim21.me/'
languageCode = 'zh-cn'
title = "Trim21's Blog"
theme = 'gokarna'
enableRobotsTXT = true
enableGitInfo = true
titleCaseStyle = 'none'

[permalinks]
posts = '/:year/:month/:slugorfilename/'

[pagination]
pagerSize = 20

[params]
dateFormat = "2006-01-02"
customCommentHTML = """
<script src="https://utteranc.es/client.js"
    repo="trim21/blog"
    issue-term="pathname"
    crossorigin="anonymous"
    async></script>
"""

[params.homeInfoParams]
Title = "Hi there"

[[params.socialIcons]]
name = 'github'
url = "https://github.com/trim21"

[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"
