# Header
menu:
  Home: /
  Archives: /archives/
#  GitHub: https://github.com/trim21

rss: /feed.xml

search: true
excerpt_link: Read More
fancybox: true

highlight_theme: normal
# Sidebar
sidebar: right

widgets:
  - recent_posts
  #- category
  #- tag
  - tagcloud
  - archive
  - links

links:
  GitHub: https://github.com/trim21

css:
  - name: fancybox
    position: afterBody
    info:
      href: https://cdn.jsdelivr.net/npm/fancybox@3.0.1/dist/css/jquery.fancybox.css
      integrity: sha256-iK+zjGHeeTQux1laFiGc4EZWPacH5acc6CnZBGji1ns=
  - name: font-awesome
    position: afterBody
    info:
      href: https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css

javascript:
  - name: jquery
    position: afterBody
    info:
      src: https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js
      integrity: sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=
  - name: fancybox
    position: afterBody
    info:
      src: https://cdn.jsdelivr.net/npm/fancybox@3.0.1/dist/js/jquery.fancybox.pack.js
      integrity: sha256-VRL0AMrD+7H9+7Apie0Jj4iir1puS6PYigObxCHqf/4=
