name: ci

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: node-${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}

      - run: yarn
        if: steps.cache-primes.outputs.cache-hit != 'true'

      - run: yarn build

      - run: cp ./_redirects public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./publish
          commit_message: deploy ${{ github.ref }}
          cname: blog.trim21.me
          github_token: ${{ secrets.GITHUB_TOKEN }}
